version: '3.1'  # Secrets are only available since this version of Docker Compose
services:
  orthanc:
    build: 
      dockerfile: Dockerfile
    # image: jodogne/orthanc
    # command: /run/secrets/  # Path to the configuration files (stored as secrets)
    ports:
      - 4242:4242
      - 8042:8042
    # secrets:
    #   - orthanc.json
    # environment:
      # ORTHANC__NAME: "HelloWorld"
      # ORTHANC__DICOM_CHECK_MODALITY_HOST: "false"
      # ORTHANC__DICOM_CHECK_CALLED_AET: "false"

      # ORTHANC_JSON: |
      #   {
      #     "Name": "orthanc-file-in-env-var",
      #     "RemoteAccessAllowed" : true,
      #     "DicomCheckCalledAet" : false,
      #     "DicomModalities" : {
      #       "PYNETDICOM" : [ "PYNETDICOM", "172.18.0.1", 4242 ]
      #     },
      #   }
# secrets:
#   orthanc.json:
#     file: orthanc.json